mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/docker'
mod 'puppetlabs/dockeragent'
#mod 'pltraining/dockeragent'
#mod 'garethr/docker'
#mod 'samuelson/samuelson-dockeragent'
