mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
#mod 'pltraining/dockeragent'
#mod 'garethr/docker'
mod 'puppetlabs/pltraining-dockeragent'
#mod 'samuelson/samuelson-dockeragent'
mod 'puppetlabs/docker'
